### PR TITLE
Branch/tag support (#6 squashed)

### PR DESCRIPTION
**Pull request by eric-wieser**
@aaronmallen, can I get you to test this?

### CODE REVIEW

**Comment by aaronmallen** [comment]
Yeah I'll get on it in the morning, is that ok?

**Comment by eric-wieser** [comment]
Sure, I just felt like you were waiting on me to get these merged!

**Comment by aaronmallen** [comment]
I have a project with  dependency on this one, but I had a long day and
it's 2. I'll get on it ASAP tomorrow.

**Comment by aaronmallen** [comment]
Tested and everything works.  However during my testing I did discover a problem with #4. given a file on the root of the computer named github:
```lua
dofile('github.rom/programs/github
```

this file is not passing arguments given to `github.rom/programs/github`

i.e.
```lua
-- command line
github clone eric-wieser/computercraft-github pr-6-squashed

-- github.rom/programs/github lines 3-4
local action = select(1,...)
print(action)

#=> nil
```

**Comment by aaronmallen** [comment]
:feelsgoodman:

**Pull request merged**
