### PR TITLE
kill tabs with fire

### PR DESCRIPTION
**Pull request by aaronmallen**
### Fixed
* converted all tabs to double space.

### CODE REVIEW

**Comment by aaronmallen** [comment]
this is literally just a find in replace for `\t` to `  ` no actual code was altered.

**Comment by eric-wieser** [comment]
Why two spaces and not four? It's a shame there's no equivalent of PEP8 for lua to give a definitive recommendation

**Comment by aaronmallen** [comment]
we can do four... I personally prefer 2 but its your code base mang...

**Comment by eric-wieser** [comment]
Also, why spaces and not tabs?

The community seems pretty divided on the issue:

Tabs:
* [MediaWiki](https://www.mediawiki.org/wiki/Manual:Coding_conventions/Lua#Whitespace)
* [Roblox](http://wiki.roblox.com/index.php?title=Lua_Style_Guide#Indentation)
* [Minetest](http://dev.minetest.net/Lua_code_style_guidelines)

Two spaces
* [Olivine labs](https://github.com/Olivine-Labs/lua-style-guide)

No strong preference
* [http://lua-users.org/wiki/LuaStyleGuide](http://lua-users.org/wiki/LuaStyleGuide)

So I'm inclined to leave this as is? Why the tab-hating?

**Comment by aaronmallen** [comment]
cool close the PR I'll redo the formatting on my other.

**Comment by eric-wieser** [comment]
Unless there's a CC-centric reason to not use tabs?

**Comment by aaronmallen** [comment]
nope just personal preference... tabs tend to break projects that use a Metric/LineLength rule, and are the devil in general. But it's all down to preference.

**Comment by eric-wieser** [comment]
"Metric/LineLength"?

**Pull request closed without merging**
