### PR TITLE
support branch/tags specification

### PR DESCRIPTION
**Pull request by aaronmallen**
### Added
* support for specifying a branch or tag when cloning a repo.

### CODE REVIEW

**Comment by aaronmallen** [comment]
going to rebase and clean up, then resubmit the pull request.

**Comment by eric-wieser** [comment]
No need to resubmit - just `push -f` and the PR will update itself

**Comment by aaronmallen** [comment]
push f is for the devil!

**Comment by eric-wieser** [comment]
`push --force-with-lease` is a little less bad

Also, github has explicit UI support for push -f in pull requests

**Pull request closed without merging**
